services:
  masa-node:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "4002:4001/tcp"
      - "4002:4001/udp"
      - "${PORT:-8081}:${PORT:-8080}"
    environment:
      BOOTNODES: "${BOOTNODES}"
      ENV: "${ENV}"
      RPC_URL: "${RPC_URL}"
      FILE_PATH: "${FILE_PATH}"
      VALIDATOR: "${VALIDATOR}"
      CACHE_PATH: "${CACHE_PATH}"
      TWITTER_SCRAPER: "${TWITTER_SCRAPER}"
      TWITTER_ACCOUNTS: "${TWITTER_ACCOUNTS}"
    volumes:
      - .:/app
      - .masa-keys:/home/masa/.masa
    restart: always

volumes:
  masa-keys:

