services:
  masa-node:
    #    network_mode: "host"
    build: .
    # optional if network_mode: "host" mode is not used
    ports:
       - "4001:4001/tcp"
       - "4001:4001/udp"
       - "8080:8080"
    environment:
      - BOOTNODES=${BOOTNODES}
      - VALIDATOR=${VALIDATOR:-false}
      - ENV=${ENV:-test}
      - RPC_URL=${RPC_URL}
      - FILE_PATH=${FILE_PATH}
      - PORT=${PORT:-8080}
      - TWITTER_SCRAPER=${TWITTER_SCRAPER}
      - TWITTER_USERNAME=${TWITTER_USERNAME}
      - TWITTER_PASSWORD=${TWITTER_PASSWORD}
      - TWITTER_2FA_CODE=${TWITTER_2FA_CODE}
      - DISCORD_SCRAPER=${DISCORD_SCRAPER}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - WEB_SCRAPER=${WEB_SCRAPER:-false}
      - TELEGRAM_SCRAPER=${TELEGRAM_SCRAPER}
      - TELEGRAM_APP_ID=${TELEGRAM_APP_ID}
      - TELEGRAM_APP_HASH=${TELEGRAM_APP_HASH}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHANNEL_USERNAME=${TELEGRAM_CHANNEL_USERNAME}
    volumes:
      - .:/app
      - .masa-keys:/home/masa/.masa
      - ./twitter_cookies.json:/home/masa/.masa/twitter_cookies.json
    restart: always

volumes:
  masa-keys:
    # This is a named volume. You can specify additional options here if needed,
    # such as setting a specific driver, driver options, or even labeling.
    # For most users, the simple declaration is sufficient.
    # Example with explicit driver (usually not required):
    # driver: local
    # Example with labels (optional):
    # labels:
    #   - "com.example.description=MASA node key storage"

